version: '3.8'

services:
  db:
    image: mysql:9.2
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nombre_base
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local

