version: '3.8'

services:
  moodle:
    image: bitnami/moodle:latest
    container_name: moodle_app
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle_password
    volumes:
      - moodle_data:/bitnami
    depends_on:
      - db
    entrypoint: ["/opt/bitnami/scripts/moodle/run.sh"]

  db:
    image: bitnami/mariadb:latest
    container_name: moodle_db
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodle_user
      - MARIADB_PASSWORD=moodle_password
    volumes:
      - db_data:/bitnami

volumes:
  moodle_data:
  db_data:
